version: 2

general:
  defaultCurrency: EUR

export:
  sheets:
    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    position:
      - spreadsheetId: anotherSpecificSheetId
        range: Funds
        data:
          - FUND
      - range: Stocks
        data:
          - STOCK
      - range: Real State CF
        data:
          - REAL_ESTATE_CF
      - range: Mixed
        data:
          - FACTORING
          - REAL_ESTATE_CF
      - range: Accounts
        data:
          - ACCOUNT

    contributions:
      - range: Contributions
        data: periodic

    transactions:
      - range: Investment TXs
        data: investment
      - range: Account TXs
        data: account
        datetimeFormat: "%-Y-%-m-%-d / %-I:%-M:%-S %Z"
        dateFormat: "%-Y-%-m-%-d"
        filters:
          - field: entity
            values: Trade Republic
      - range: All TXs
        data:
          - investment
          - account

    historic:
      - range: Factoring Historic
        # "data" config entry is not available for historic, use filters instead
        filters:
          - field: product_type
            values: FACTORING
          - field: state
            values:
              - COLLECTED
              - MANAGING_COLLECTION

importing:
  sheets:
    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    position:
      - spreadsheetId: oneSpecificSheetId
        range: Deposits
        data: DEPOSIT
        datetimeFormat: "%d/%m/%Y %H:%M:%S"
        dateFormat: "%d/%m/%Y"

    transactions:
      - range: Investment TXs
        data: investment

assets:
  crypto:
    stablecoins:
      - USDT
      - USDC
      - USDe
      - DAI
      - USD1
      - BUSD
      - PYUSD
      - FDUSD
      - TUSD
      - USDD
      - GUSD
      - USDP
      - LUSD
      - cUSD
      - OUSD
      - FRAX
      - sUSD
      - USDX
      - USDY
      - USYC
      - EURC
      - EURS
      - EURT
      - PAXG
      - XAUT
      - JPYC
    hideUnknownTokens: true