version: 2

general:
  defaultCurrency: EUR

export:
  sheets:
    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    position:
      - spreadsheetId: anotherSpecificSheetId
        range: Funds
        data:
          - FUND
      - range: Stocks
        data:
          - STOCK
        template:
          id: 0ddb21e8-adc7-4d0d-970e-a3e0cfff1ea2
      - range: Real State CF
        data:
          - REAL_ESTATE_CF
      - range: Mixed
        data:
          - FACTORING
          - REAL_ESTATE_CF
      - range: Accounts
        lastUpdate: yes
        data:
          - ACCOUNT

    contributions:
      - range: Contributions

    transactions:
      - range: Investment TXs
        data:
          - STOCK_ETF
          - FUND
      - range: Account TXs
        data:
          - ACCOUNT
        datetimeFormat: "%-Y-%-m-%-d / %-I:%-M:%-S %Z"
        dateFormat: "%-Y-%-m-%-d"
        filters:
          - field: source
            values: REAL
          - field: entity
            values: Trade Republic
      - range: All TXs
        data:
          - STOCK_ETF
          - FUND
          - FUND_PORTFOLIO
          - FACTORING
          - REAL_ESTATE_CF
          - ACCOUNT

    historic:
      - range: Factoring Historic
        data:
          - FACTORING
        filters:
          - field: state
            values:
              - COLLECTED
              - MANAGING_COLLECTION

importing:
  sheets:
    globals:
      spreadsheetId: defaultSheetId
      datetimeFormat: "%d/%m/%Y %H:%M:%S"
      dateFormat: "%d/%m/%Y"

    position:
      - spreadsheetId: oneSpecificSheetId
        range: Deposits
        data: DEPOSIT
        datetimeFormat: "%d/%m/%Y %H:%M:%S"
        dateFormat: "%d/%m/%Y"
        template:
          id: af5fed95-c282-4df9-ab32-584e715cd29d

    transactions:
      - range: Investment TXs
        template:
          id: af5fed95-c282-4df9-ab32-584e715cd29d
          params:
            entity: ABank
        data: STOCK_ETF

assets:
  crypto:
    stablecoins:
      - USDT
      - USDC
      - USDe
      - DAI
      - USD1
      - BUSD
      - PYUSD
      - FDUSD
      - TUSD
      - USDD
      - GUSD
      - USDP
      - LUSD
      - cUSD
      - OUSD
      - FRAX
      - sUSD
      - USDX
      - USDY
      - USYC
      - EURC
      - EURS
      - EURT
      - PAXG
      - XAUT
      - JPYC
    hideUnknownTokens: true